<?php

namespace App\Console\Commands;

use App\Models\Invoice;
use App\Models\Lease;
use Carbon\Carbon;
use Illuminate\Console\Command;

class GenerateMonthlyInvoices extends Command
{
    protected $signature = 'invoices:generate
                            {--month= : Target month in YYYY-MM format (default: current month)}
                            {--h1 : Auto mode — only generate for leases whose due date is tomorrow (H-1)}';

    protected $description = 'Generate monthly invoices for all active leases';

    public function handle(): int
    {
        $h1Mode = $this->option('h1');

        // In H-1 mode, resolve the target month based on tomorrow's date
        if ($h1Mode) {
            $tomorrow = now()->addDay();
            // If tomorrow is the 1st, generate for next month (edge case)
            $targetMonth = Carbon::create($tomorrow->year, $tomorrow->month, 1);
            $monthYear = $targetMonth->format('Y-m');
            $dueTomorrow = $tomorrow->day;
            $this->info("[H-1] Generating invoices for leases with due_date_per_month = {$dueTomorrow} (tomorrow), month: {$monthYear}");
        } else {
            $monthYear = $this->option('month') ?? now()->format('Y-m');

            if (!preg_match('/^\d{4}-(0[1-9]|1[0-2])$/', $monthYear)) {
                $this->error("Invalid month format. Use YYYY-MM (e.g. 2026-03)");
                return self::FAILURE;
            }

            $targetMonth = Carbon::createFromFormat('Y-m', $monthYear);
        }

        $leases = Lease::where('status', 'active')
            ->where('start_date', '<=', $targetMonth->copy()->endOfMonth())
            ->where('end_date', '>=', $targetMonth->copy()->startOfMonth())
            ->with('room.roomType')
            ->get();

        // In H-1 mode, only process leases due tomorrow
        if ($h1Mode) {
            $leases = $leases->filter(fn($l) => $l->due_date_per_month == $dueTomorrow);
        }

        if ($leases->isEmpty()) {
            $this->info("Tidak ada lease yang perlu dibuatkan invoice untuk bulan {$monthYear}.");
            return self::SUCCESS;
        }

        $created = 0;
        $skipped = 0;

        foreach ($leases as $lease) {
            $exists = Invoice::where('lease_id', $lease->id)
                ->where('month_year', $monthYear)
                ->exists();

            if ($exists) {
                $skipped++;
                continue;
            }

            $dueDay = min($lease->due_date_per_month, $targetMonth->daysInMonth);
            $dueDate = $targetMonth->copy()->day($dueDay);

            Invoice::create([
                'lease_id' => $lease->id,
                'amount' => $lease->room->roomType->price,
                'month_year' => $monthYear,
                'status' => 'unpaid',
                'reference_number' => Invoice::generateInvoiceNumber(),
                'due_date' => $dueDate,
                'created_by' => null, // null = auto-generated by system
            ]);

            $created++;
        }

        $this->info("Selesai! {$created} invoice dibuat, {$skipped} dilewati (sudah ada).");

        return self::SUCCESS;
    }
}
